name: AKS Deployment

on:
  workflow_run:
    workflows: ["CI/CD front end"]
    types:
      - completed 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
    
      - name: Select Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group stageDevops --name stage

      - name: Modify backend deployment file
        run: |
          sed -i "s|image: mokhtar1234/ecommerce:back-app-.*|image: mokhtar1234/ecommerce:back-app-${{ github.sha }}|" manifests/backdeployment.yml

      - name: Deploy DB postgre
        run: |
          cd manifests
          kubectl apply -f db-deployment.yaml
          kubectl apply -f db-service.yaml

      - name: Deploy back end 
        run: |
          cd manifests
          kubectl apply -f backdeployment.yml
          kubectl apply -f backservice.yml

      - name: Modify frontend deployment file
        run: |
          sed -i "s|image: mokhtar1234/ecommerce:front-app-.*|image: mokhtar1234/ecommerce:front-app-${{ github.sha }}|" manifests/frontend-deployment.yaml

      - name: Deploy front end 
        run: |
          cd manifests
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f frontend-service.yaml
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }} 