name: CI/CD back end 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
   
jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          cd backend
          mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Push back end image
      uses: docker/build-push-action@v4
      with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:back-app-${{ github.sha }}
    


    

